### PR TITLE
CI features

### PR DESCRIPTION
**Pull request by sadasant**
We'll be enforcing CHANGELOG updates soon :)

### CODE REVIEW

**Comment by sadasant** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  /home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  Error: Could not find a `dangerfile.js` or `dangerfile.ts` in the current working directory.
    at Object.dangerfilePath (/home/circleci/project/node_modules/danger/distribution/commands/utils/file-utils.js:20:11)
    at Object.<anonymous> (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:75:43)
    at step (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:33:23)
    at Object.next (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:14:53)
    at fulfilled (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by aitbw** [comment]
Re: changelogs, we could definitely use [this](https://github.com/skywinder/github-changelog-generator)

**Comment by sadasant** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  /home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  Error: Could not find a `dangerfile.js` or `dangerfile.ts` in the current working directory.
    at Object.dangerfilePath (/home/circleci/project/node_modules/danger/distribution/commands/utils/file-utils.js:20:11)
    at Object.<anonymous> (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:75:43)
    at step (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:33:23)
    at Object.next (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:14:53)
    at fulfilled (/home/circleci/project/node_modules/danger/distribution/commands/danger-runner.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sadasant** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error TypeError
```
require(...) is not a function
TypeError: require(...) is not a function
    at Object.<anonymous> (dangerfile.js:13:45)
    at Module._compile (module.js:624:30)
    at requireFromString (/home/circleci/project/node_modules/danger/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:102:21)
    at step (/home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at Object.runDangerfileEnvironment (/home/circleci/project/node_modules/danger/distribution/runner/runners/inline.js:69:12)
```
### Dangerfile
```
 6| 
 7| if (danger.github.pr.requested_reviewers.length < 1)
 8|   warn(`You should add at least one reviewer to the PR`)
 9| 
10| if (danger.git.modified_files.includes('CHANGELOG.md'))
11|   fail('Please DO NOT CHANGE the CHANGELOG.')
12| 
-----------------------------------------------^
13| schedule(require('danger-plugin-spellcheck')())
14| 
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sadasant** [comment]
@aitbw I'm going to use this: https://github.com/tecnoyucas/meta/pull/27/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7

**Comment by stefanmaric** [comment]
> @aitbw I'm going to use this: https://github.com/tecnoyucas/meta/pull/27/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7

I'm just curious: why are we going to force [Conventional Commit](https://conventionalcommits.org/) (the default of conventional-changelog)? Since it is intended for library authors, which consumers require respect of API compatibility between version.

**Pull request merged**
