### PR TITLE
added TecnoYucas SVG degraded logo

### PR DESCRIPTION
**Pull request by sergebruni**

### CODE REVIEW

**Comment by aitbw** [comment]
Thoughts on this, @sadasant? I think the original version is way better and enough (for now) for our purposes

**Comment by sadasant** [comment]
@aitbw I really want this merged

**Comment by sadasant** [comment]
@sergebruni thank you!!!

**Comment by stefanmaric** [comment]
Hey guys, as heads up, this SVG has some hidden raster images embedded that we should remove.

@sergebruni also, isn't it possible to reduce the number of layers and improve the gradient quality using actual gradients?

See: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients

**Comment by sergebruni** [comment]
@stefanmaric it is possible, actually i manage to improve the quality of the svg and reduce considerably the amount of layers in it, i will make a new PR

**Pull request merged**
